Blitz.WebMVC/Controllers/BlitzController.cs
using Microsoft.AspNet.Identity;
using SalesBlitz.Data;
using SalesBlitz.Models;
using SalesBlitz.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blitz.WebMVC.Controllers
{
    [Authorize]
    public class BlitzController : Controller
    {
        // GET: Blitz
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BlitzService(userId);
            var model = service.GetBlitz();

            return View(model);

        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlitzCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateBlitzService();

            if (service.CreateBlitz(model))
            {
                TempData["SaveResult"] = "Your Blitz was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Blitz could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateBlitzService();
            var model = svc.GetBlitzById(id);

            return View(model);
        }
        public BlitzService CreateBlitzService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BlitzService(userId);
            return service;
        }

        public ActionResult Edit(int id)
        {
            var service = CreateBlitzService();
            var detail = service.GetBlitzById(id);
            var model =
                new BlitzEdit
                {
                    BlitzId = detail.BlitzId,
                    Name = detail.Name,
                    Location = detail.Location,
                    Date  = detail.Date
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BlitzEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.BlitzId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateBlitzService();

            if (service.UpdateBlitz(model))
            {
                TempData["SaveResult"] = "Your Blitz was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Blitz could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateBlitzService();
            var model = svc.GetBlitzById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        
        public ActionResult DeletePost(int id)
        {
            var service = CreateBlitzService();

            service.DeleteBlitz(id);

            TempData["SaveResult"] = "Your Blitz was deleted";

            return RedirectToAction("Index");
        }
    }
}

Blitz.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    body {
        background-image: url(Image/Operator.jpg); 
        background-size: 100%;
        background-repeat: no-repeat;
    }

    .body-content {
        background-color: white;
        border-bottom: 0px solid black;
        border-left: 0px solid black;
        border-right: 0px solid black;
        border-radius: 0px 0px 15px 15px;
        background-image: url(Image/Operator.jpg);
        background-size: 100%;
        background-repeat: no-repeat;
    }
</style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <script src="bootstrap/scripts/jquery.min.js"></script>
      <script src="/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-static-top" data-toggle="collapse" data-target=".navbar-custom">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sales Blitz", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
            <div class="navbar-custom focus">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Blitzes", "Index", "Blitz")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Lead", "Index", "Lead")</li>
                    



                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sales Solutions Group LLC </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>